### ISSUE TITLE
Tinkerpop enable Vertexium

### ISSUE THREAD

**Issue by srfarley** [visallo/vertexium#107]
Many similar graph databases are on this list: http://tinkerpop.apache.org/providers.html

**Comment by aliammar7** [comment]
can we use now vertexium with tinkerpop 3?

**Comment by joeferner** [comment]
Sorry, no. I have deprecated and removed tinkerpop/blueprints support

**Comment by aliammar7** [comment]
Thanks for your reply 
can we traverse the graph using vertexium ?

**Comment by aliammar7** [comment]
sorry i have another question please . vertexium only support accumulo storage? is there any plan to support another storage like berkley or cassandra?
